# Generated by Django 4.0.3 on 2022-03-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modigy_date',
            new_name='modify_date',
        ),
    ]
